service: take-home-assessment

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  environment: 
    PYTHONPATH: '/src/exampleco:'


functions:
  get_all_orders:
    handler: handler.get_all_orders
    events:
      - httpApi:
          path: /orders
          method: get

  get_all_services:
    handler: service_handler.get_all_services
    events:
      - httpApi:
          path: /services
          method: get
    timeout: 30

  get_service_by_id:
    handler: service_handler.get_service_by_id
    description: Get Service By Id
    events:
      - httpApi:
          path: /services/{id}
          method: get
    timeout: 30