"""Added service_id FK

Revision ID: 88771472e4fa
Revises: 64336cae7a87
Create Date: 2022-07-28 21:38:57.395363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88771472e4fa'
down_revision = '64336cae7a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('service_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order_items', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'service_id')
    # ### end Alembic commands ###
